const assert = require("node:assert/strict");
const { initialPlanning, planUpdate } = require("../lib/planning");
const { computeAttendance } = require("../lib/attendance");
const state = initialPlanning();
const admin = { id: "a", name: "张三", center: "行政事务中心", studentNo: "1", week: 1, weekday: "星期一", shift: "一二节" };
const data = { ...admin, id: "b", studentNo: "2", center: "大数据中心" };
const db = { schedules: [admin], checkins: [], reviews: [] };
const added = planUpdate(db, state, { expectedRevision: 0 }, [data]);
assert.equal(added.schedules.length, 2);
assert.equal(added.schedules[0].id, "a");
assert.equal(added.impact[0].action, "新增");
const changed = planUpdate({ ...db, schedules: added.schedules }, state, { expectedRevision: 0 }, [{ ...admin, shift: "三四节" }]);
assert.equal(changed.schedules.length, 2);
assert.ok(changed.schedules.some(row => row.center === "大数据中心"));
assert.equal(changed.impact[0].action, "更新");
assert.throws(() => planUpdate(db, state, { expectedRevision: 1 }, [admin]), /刷新/);
assert.throws(() => planUpdate(db, state, { expectedRevision: 0, mode: "new-batch" }, [admin]), /开启新学期/);
const before = computeAttendance({ ...db, calendar: state.calendar }, { week: 1, now: "2026-09-05T00:00:00Z" });
assert.equal(before.rows[0].date, "2026-09-07");
assert.equal(before.rows[0].status, "未开始");
assert.equal(before.rows[0].needsReview, false);
console.log("Center merge, stale revision and dated attendance tests passed.");
